"""
政治新闻技能包
"""

from .pol_01 import (
    POL_01_METADATA as POL_01_METADATA,
    INPUT_SCHEMA as POL_01_INPUT_SCHEMA,
    OUTPUT_SCHEMA as POL_01_OUTPUT_SCHEMA,
    WORKFLOW as POL_01_WORKFLOW,
    POL_01_ARTICLE_PROMPT,
    NEWS_ARTICLE_TEMPLATE,
    RESTRICTED_WORDS,
    SUGGESTED_WORDS,
    validate_article,
    format_for_platform,
    format_wechat,
    format_weibo,
    format_print,
)

from .pol_04 import (
    POL_04_METADATA,
    INPUT_SCHEMA as POL_04_INPUT_SCHEMA,
    OUTPUT_SCHEMA as POL_04_OUTPUT_SCHEMA,
    SOURCE_LEVELS,
    FORBIDDEN_WORDS,
    BREAKING_TEMPLATE,
    ROLLING_UPDATE_TEMPLATE,
    rate_source,
    verify_facts,
    generate_timestamp,
    check_forbidden_words,
    validate_breaking_report,
    format_breaking_report,
    generate_rolling_update,
    detect_urgency_level,
    ALERT_KEYWORDS,
)

from .pol_05 import (
    POL_05_METADATA,
    INPUT_SCHEMA as POL_05_INPUT_SCHEMA,
    OUTPUT_SCHEMA as POL_05_OUTPUT_SCHEMA,
    PRESS_CONFERENCE_TEMPLATE,
    CONTROVERSY_TYPES,
    SPEAKER_PLACEHOLDERS,
    TRANSCRIPT_TEMPLATE,
    KEY_POINT_TEMPLATE,
    CONTROVERSY_TEMPLATE,
    format_transcript,
    extract_key_points,
    identify_controversy,
    segment_press_conference,
    format_article,
    ASR_TRANSCRIBE_PROMPT,
    SPEAKER_REPLACE_PROMPT,
    STRUCTURE_SEGMENT_PROMPT,
    CONTROVERSY_IDENTIFY_PROMPT,
    KEY_POINTS_EXTRACT_PROMPT,
    ARTICLE_GENERATE_PROMPT,
)

__all__ = [
    # pol_01
    "POL_01_METADATA",
    "POL_01_INPUT_SCHEMA",
    "POL_01_OUTPUT_SCHEMA",
    "POL_01_WORKFLOW",
    "POL_01_ARTICLE_PROMPT",
    "NEWS_ARTICLE_TEMPLATE",
    "RESTRICTED_WORDS",
    "SUGGESTED_WORDS",
    "validate_article",
    "format_for_platform",
    "format_wechat",
    "format_weibo",
    "format_print",
    # pol_04
    "POL_04_METADATA",
    "POL_04_INPUT_SCHEMA",
    "POL_04_OUTPUT_SCHEMA",
    "SOURCE_LEVELS",
    "FORBIDDEN_WORDS",
    "BREAKING_TEMPLATE",
    "ROLLING_UPDATE_TEMPLATE",
    "rate_source",
    "verify_facts",
    "generate_timestamp",
    "check_forbidden_words",
    "validate_breaking_report",
    "format_breaking_report",
    "generate_rolling_update",
    "detect_urgency_level",
    "ALERT_KEYWORDS",
    # pol_05
    "POL_05_METADATA",
    "POL_05_INPUT_SCHEMA",
    "POL_05_OUTPUT_SCHEMA",
    "PRESS_CONFERENCE_TEMPLATE",
    "CONTROVERSY_TYPES",
    "SPEAKER_PLACEHOLDERS",
    "TRANSCRIPT_TEMPLATE",
    "KEY_POINT_TEMPLATE",
    "CONTROVERSY_TEMPLATE",
    "format_transcript",
    "extract_key_points",
    "identify_controversy",
    "segment_press_conference",
    "format_article",
    "ASR_TRANSCRIBE_PROMPT",
    "SPEAKER_REPLACE_PROMPT",
    "STRUCTURE_SEGMENT_PROMPT",
    "CONTROVERSY_IDENTIFY_PROMPT",
    "KEY_POINTS_EXTRACT_PROMPT",
    "ARTICLE_GENERATE_PROMPT",
]
